quiz-page
MikhailBiltsevich/quiz-app-frontend pull request #12
Opened 2021-02-17 16:34 UTC by MikhailBiltsevich

I've implemented html-web page without interactivity. I'm going to read about state hook and general info about hooks and add it. I think hooks is necessary, because I didn't use `React.Component` class.

Here the screenshot of my today's work (17/02/2021)
![Снимок экрана (34)](https://user-images.githubusercontent.com/12757601/108235625-0d0d4900-7157-11eb-9b65-dc6e0c2c8904.png)

2021-02-22 09:47 UTC, MikhailBiltsevich commented
I've add Redux (reduxToolkit, react-redux and @types/react-redux). I created store and one slice. Also for data I add several interfaces in file `types.ts`

2021-02-23 11:27 UTC, MikhailBiltsevich commented
I've implemented adding, editing and deleting questions. I didn't realize delete answers yet. I think my code should refactor, but it now it works. You can check functionality

2021-03-01 14:45 UTC, DieselWolf requested changes

2021-03-01 14:45 UTC, DieselWolf commented on src/pages/quiz/QuizPage.tsx
> +            <fieldset>
would be great to create a new component, like:  <Fieldset/>

2021-03-02 10:22 UTC, MikhailBiltsevich commented on src/pages/quiz/QuizPage.tsx
> +  const questionType = [
I've moved this const to `src/app/types.ts`

2021-03-02 14:57 UTC, MikhailBiltsevich commented on src/app/slices/quizSlice.ts
> +export default quizSlice.reducer;
I'll read the diffrence later

2021-03-02 14:59 UTC, MikhailBiltsevich commented on src/pages/quiz/QuizPage.tsx
> +            <fieldset>
I should create component for what? I can't understand by selected rows

2021-03-02 15:02 UTC, MikhailBiltsevich commented
I've created two container components and some refactor. Also I've moved `questionTypes` const to types.ts file

2021-03-02 16:12 UTC, DieselWolf approved these changes

2021-03-04 13:37 UTC, merged