Feature header component
MikhailBiltsevich/quiz-app-frontend pull request #4
Opened 2021-02-05 18:02 UTC by MikhailBiltsevich

`Header` displays on the screenshot below (user have authentificated)
![Снимок экрана (30)](https://user-images.githubusercontent.com/12757601/107070929-07c60b00-67f5-11eb-813a-8ccd86f06745.png)

2021-02-08 14:45 UTC, DieselWolf requested changes

2021-02-08 14:45 UTC, DieselWolf commented on src/components/HeaderComponent/HeaderComponent.tsx
> +          <ButtonComponent classNames={['button', 'col-sm-12', 'col-md-2']} handlerClick={signOutHandler} text='Sign out' />
If you decide to use Button component on your Header Component, you must create special section for Button, it shouldn't be hard coded component.
The same for text and other components which you will use in header

2021-02-08 23:24 UTC, MikhailBiltsevich commented on src/components/HeaderComponent/HeaderComponent.tsx
> +          <ButtonComponent classNames={['button', 'col-sm-12', 'col-md-2']} handlerClick={signOutHandler} text='Sign out' />
It's about only components in Header? Do you mean that I have to wrap each component that located in Header?

2021-02-10 08:19 UTC, DieselWolf requested changes

2021-02-10 08:19 UTC, DieselWolf commented on src/components/HeaderComponent/HeaderComponent.tsx
> +  content?: JSX.Element
I'm not sure about this type
I think it should related to component

2021-02-10 22:55 UTC, MikhailBiltsevich commented
Hi! I did some mistake, when commit changes by `git commit --ammend` after pushing branch into remote repository. I used `any` type for `content` prop. So we can use string or html-template for example.

2021-02-11 16:22 UTC, DieselWolf approved these changes

2021-02-11 17:56 UTC, merged