sign-in-page
MikhailBiltsevich/quiz-app-frontend pull request #6
Opened 2021-02-08 14:08 UTC by MikhailBiltsevich

I have started implementing 'sign in' page. Please check code. You don't have to approve this PR. But I need a feedback. I don't understand why I can use ButtonComponent without `handler` property. Maybe my interface implementing is wrong?

2021-02-10 08:13 UTC, DieselWolf requested changes

2021-02-10 08:13 UTC, DieselWolf commented on src/pages/sign-in/SignInPage.tsx
> +        <InputComponent id='login' label='Username' type='text' handler={() => { }} />
i'm not sure about this handler name...
handle what? 

https://medium.com/javascript-in-plain-english/handy-naming-conventions-for-event-handler-functions-props-in-react-fc1cbb791364

2021-02-10 23:40 UTC, MikhailBiltsevich commented on src/pages/sign-in/SignInPage.tsx
> +        <InputComponent id='login' label='Username' type='text' handler={() => { }} />
According to article that you sent I will fix it for InputComponent and ButtonComponent

2021-02-15 10:50 UTC, DieselWolf approved these changes

2021-02-15 10:58 UTC, merged